////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.18051
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//using SharpKit.JavaScript;
//namespace Neptuo.Templates
//{
//    [JsType(JsMode.Clr, Filename = "res/View.js")]
//    public sealed class View_9741084CDDEB89E6278CC0A58C5F284F84983F2D : Neptuo.Templates.GeneratedView, System.IDisposable
//    {
//        protected override void BindView(GeneratedView view)
//        {
//            this.Content.Add("<div>");
//            this.Content.Add(this.field1_Create());
//            this.Content.Add(this.field4_Create());
//            this.Content.Add(this.field7_Create());
//            this.Content.Add(this.field10_Create());
//            this.Content.Add("</div>");
//        }
//        private Test.Templates.Controls.PanelControl field1_Create()
//        {
//            Test.Templates.Controls.PanelControl field1 = new Test.Templates.Controls.PanelControl();
//            this.componentManager.AddComponent(field1, this.field1_Bind);
//            return field1;
//        }
//        private void field1_Bind(Test.Templates.Controls.PanelControl field1)
//        {
//            field1.Content = new System.Collections.Generic.List<object>();
//            field1.Content.Add(" \r\n        Street: \r\n        ");
//            field1.Content.Add(this.field2_Create());
//        }
//        private Test.Templates.Controls.TextBoxControl field2_Create()
//        {
//            Test.Templates.Controls.TextBoxControl field2 = new Test.Templates.Controls.TextBoxControl();
//            this.componentManager.AddComponent(field2, this.field2_Bind);
//            return field2;
//        }
//        private void field2_Bind(Test.Templates.Controls.TextBoxControl field2)
//        {
//            field2.Name = "street";
//            field2.Text = ((string)(this.field3_Create().ProvideValue(new Neptuo.Templates.Extensions.DefaultExtensionContext(field2, field2.GetType().GetProperty("Text"), this.dependencyProvider))));
//        }
//        private Test.Templates.Extensions.BindingExtension field3_Create()
//        {
//            Test.Templates.Extensions.BindingExtension field3 = new Test.Templates.Extensions.BindingExtension(((Test.Templates.Data.DataStorage)(this.dependencyProvider.Resolve(typeof(Test.Templates.Data.DataStorage), null))), null);
//            field3.Expression = "Street";
//            return field3;
//        }
//        private Test.Templates.Controls.PanelControl field4_Create()
//        {
//            Test.Templates.Controls.PanelControl field4 = new Test.Templates.Controls.PanelControl();
//            this.componentManager.AddComponent(field4, this.field4_Bind);
//            return field4;
//        }
//        private void field4_Bind(Test.Templates.Controls.PanelControl field4)
//        {
//            field4.Content = new System.Collections.Generic.List<object>();
//            field4.Content.Add("\r\n        House Number:\r\n        ");
//            field4.Content.Add(this.field5_Create());
//        }
//        private Test.Templates.Controls.TextBoxControl field5_Create()
//        {
//            Test.Templates.Controls.TextBoxControl field5 = new Test.Templates.Controls.TextBoxControl();
//            this.componentManager.AddComponent(field5, this.field5_Bind);
//            return field5;
//        }
//        private void field5_Bind(Test.Templates.Controls.TextBoxControl field5)
//        {
//            field5.Name = "housenumber";
//            field5.Text = ((string)(this.field6_Create().ProvideValue(new Neptuo.Templates.Extensions.DefaultExtensionContext(field5, field5.GetType().GetProperty("Text"), this.dependencyProvider))));
//        }
//        private Test.Templates.Extensions.BindingExtension field6_Create()
//        {
//            Test.Templates.Extensions.BindingExtension field6 = new Test.Templates.Extensions.BindingExtension(((Test.Templates.Data.DataStorage)(this.dependencyProvider.Resolve(typeof(Test.Templates.Data.DataStorage), null))), null);
//            field6.Expression = "HouseNumber";
//            return field6;
//        }
//        private Test.Templates.Controls.PanelControl field7_Create()
//        {
//            Test.Templates.Controls.PanelControl field7 = new Test.Templates.Controls.PanelControl();
//            this.componentManager.AddComponent(field7, this.field7_Bind);
//            return field7;
//        }
//        private void field7_Bind(Test.Templates.Controls.PanelControl field7)
//        {
//            field7.Content = new System.Collections.Generic.List<object>();
//            field7.Content.Add(" \r\n        City: \r\n        ");
//            field7.Content.Add(this.field8_Create());
//        }
//        private Test.Templates.Controls.TextBoxControl field8_Create()
//        {
//            Test.Templates.Controls.TextBoxControl field8 = new Test.Templates.Controls.TextBoxControl();
//            this.componentManager.AddComponent(field8, this.field8_Bind);
//            return field8;
//        }
//        private void field8_Bind(Test.Templates.Controls.TextBoxControl field8)
//        {
//            field8.Name = "city";
//            field8.Text = ((string)(this.field9_Create().ProvideValue(new Neptuo.Templates.Extensions.DefaultExtensionContext(field8, field8.GetType().GetProperty("Text"), this.dependencyProvider))));
//        }
//        private Test.Templates.Extensions.BindingExtension field9_Create()
//        {
//            Test.Templates.Extensions.BindingExtension field9 = new Test.Templates.Extensions.BindingExtension(((Test.Templates.Data.DataStorage)(this.dependencyProvider.Resolve(typeof(Test.Templates.Data.DataStorage), null))), null);
//            field9.Expression = "City";
//            return field9;
//        }
//        private Test.Templates.Controls.PanelControl field10_Create()
//        {
//            Test.Templates.Controls.PanelControl field10 = new Test.Templates.Controls.PanelControl();
//            this.componentManager.AddComponent(field10, this.field10_Bind);
//            return field10;
//        }
//        private void field10_Bind(Test.Templates.Controls.PanelControl field10)
//        {
//            field10.Content = new System.Collections.Generic.List<object>();
//            field10.Content.Add("\r\n        Postal code:\r\n        ");
//            field10.Content.Add(this.field11_Create());
//        }
//        private Test.Templates.Controls.TextBoxControl field11_Create()
//        {
//            Test.Templates.Controls.TextBoxControl field11 = new Test.Templates.Controls.TextBoxControl();
//            this.componentManager.AddComponent(field11, this.field11_Bind);
//            return field11;
//        }
//        private void field11_Bind(Test.Templates.Controls.TextBoxControl field11)
//        {
//            field11.Name = "postalcode";
//            field11.Text = ((string)(this.field12_Create().ProvideValue(new Neptuo.Templates.Extensions.DefaultExtensionContext(field11, field11.GetType().GetProperty("Text"), this.dependencyProvider))));
//        }
//        private Test.Templates.Extensions.BindingExtension field12_Create()
//        {
//            Test.Templates.Extensions.BindingExtension field12 = new Test.Templates.Extensions.BindingExtension(((Test.Templates.Data.DataStorage)(this.dependencyProvider.Resolve(typeof(Test.Templates.Data.DataStorage), null))), null);
//            field12.Expression = "PostalCode";
//            return field12;
//        }
//    }
//}
