//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neptuo.Web.Framework
{
    using System;
    using Neptuo.Web;
    using Neptuo.Web.Framework;
    using Neptuo.Web.Framework.Controls;
    using Neptuo.Web.Framework.Extensions;
    using Neptuo.Web.Framework.Observers;

    public sealed class GeneratedView : Neptuo.Web.Framework.BaseGeneratedView, Neptuo.Web.Framework.IGeneratedView, System.IDisposable
    {
        private PanelControl field1;
        private VisibleObserver field2;
        private TextBoxControl field3;
        private BindingExtension field4;
        private ValidationObserver field5;

        protected override void CreateViewPageControls()
        {
            viewPage.Content = new ComponentManagerCollection<object>(componentManager, "Content", viewPage);
            field1 = field1_Create();
            componentManager.AddComponent(viewPage, "Content", field1, field1_Bind);
        }

        private PanelControl field1_Create()
        {
            return new PanelControl();
        }

        private void field1_Bind()
        {
            field1.Content = new ComponentManagerCollection<object>(componentManager, "Content", field1);
            field3 = field3_Create();
            componentManager.AddComponent(field1, "Content", field3, field3_Bind);
            field1.ComponentManager = componentManager;
            field2 = field2_Create();
            componentManager.AttachObserver(field1, field2, field2_Bind);
        }

        private VisibleObserver field2_Create()
        {
            return new VisibleObserver();
        }

        private void field2_Bind()
        {
            field2.Visible = true;
        }

        private TextBoxControl field3_Create()
        {
            return new TextBoxControl();
        }

        private void field3_Bind()
        {
            field3.Name = "FullName";
            field4 = field4_Create();
            field4_Bind();
            field3.Text = (string)field4.ProvideValue();
            field5 = field5_Create();
            componentManager.AttachObserver(field3, field5, field5_Bind);
            componentManager.AttachObserver(field3, field5, field5_Bind2);
            componentManager.AttachObserver(field3, field5, field5_Bind3);
        }

        private BindingExtension field4_Create()
        {
            return new BindingExtension();
        }

        private void field4_Bind()
        {
            field4.Expression = "John Doe";
        }

        private ValidationObserver field5_Create()
        {
            ValidationObserver item = new ValidationObserver();
            item.MinLength = -1;
            item.MaxLength = -1;
            return item;
        }

        private void field5_Bind()
        {
            field5.MinLength = 2;
        }

        private void field5_Bind2()
        {
            field5.MaxLength = 10;
        }

        private void field5_Bind3()
        {
            field5.ErrorMessage = "Provide a valid value!";
        }
    }
}
