//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SharpKit.JavaScript;
namespace Neptuo.Templates
{
    [JsType(JsMode.Clr, Filename = "res/View.js")]
    public sealed class View_C612CAF502A06BAAC6171B58D1EA2F61EC9D6D55 : Neptuo.Templates.GeneratedView, System.IDisposable
    {
        protected override void BindView(GeneratedView view)
        {
            this.Content.Add("<div><h:panel> \r\n        Street: \r\n        <h:textbox name=\"street\" />");
            this.Content.Add("</h:panel>");
            this.Content.Add("</div>");
        }
    }
}
