//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SharpKit.JavaScript;
namespace Neptuo.Templates
{
    [JsType(JsMode.Clr, Filename = "res/View.js")]
    public sealed class View_9741084CDDEB89E6278CC0A58C5F284F84983F2D : Neptuo.Templates.BaseGeneratedView, System.IDisposable
    {
        protected override void CreateViewPageControls(Neptuo.Templates.IViewPage viewPage)
        {
            this.Content.Add("<div>");
            this.Content.Add(this.field1_Create());
            this.Content.Add(this.field4_Create());
            this.Content.Add(this.field7_Create());
            this.Content.Add(this.field10_Create());
            this.Content.Add("</div>");
        }
        private TestConsoleNG.Controls.PanelControl field1_Create()
        {
            TestConsoleNG.Controls.PanelControl field1 = new TestConsoleNG.Controls.PanelControl(this.componentManager);
            this.componentManager.AddComponent(field1, this.field1_Bind);
            return field1;
        }
        private void field1_Bind(TestConsoleNG.Controls.PanelControl field1)
        {
            field1.Content = new System.Collections.Generic.List<object>();
            field1.Content.Add(" \r\n        Street: \r\n        ");
            field1.Content.Add(this.field2_Create());
        }
        private TestConsoleNG.Controls.TextBoxControl field2_Create()
        {
            TestConsoleNG.Controls.TextBoxControl field2 = new TestConsoleNG.Controls.TextBoxControl(this.componentManager);
            this.componentManager.AddComponent(field2, this.field2_Bind);
            return field2;
        }
        private void field2_Bind(TestConsoleNG.Controls.TextBoxControl field2)
        {
            field2.Name = "street";
            field2.Text = ((string)(this.field3_Create().ProvideValue(new Neptuo.Templates.Extensions.DefaultMarkupExtensionContext(field2, field2.GetType().GetProperty("Text"), this.dependencyProvider))));
        }
        private TestConsoleNG.Extensions.BindingExtension field3_Create()
        {
            TestConsoleNG.Extensions.BindingExtension field3 = new TestConsoleNG.Extensions.BindingExtension(((TestConsoleNG.Data.DataStorage)(this.dependencyProvider.Resolve(typeof(TestConsoleNG.Data.DataStorage), null))));
            field3.Expression = "Street";
            return field3;
        }
        private TestConsoleNG.Controls.PanelControl field4_Create()
        {
            TestConsoleNG.Controls.PanelControl field4 = new TestConsoleNG.Controls.PanelControl(this.componentManager);
            this.componentManager.AddComponent(field4, this.field4_Bind);
            return field4;
        }
        private void field4_Bind(TestConsoleNG.Controls.PanelControl field4)
        {
            field4.Content = new System.Collections.Generic.List<object>();
            field4.Content.Add("\r\n        House Number:\r\n        ");
            field4.Content.Add(this.field5_Create());
        }
        private TestConsoleNG.Controls.TextBoxControl field5_Create()
        {
            TestConsoleNG.Controls.TextBoxControl field5 = new TestConsoleNG.Controls.TextBoxControl(this.componentManager);
            this.componentManager.AddComponent(field5, this.field5_Bind);
            return field5;
        }
        private void field5_Bind(TestConsoleNG.Controls.TextBoxControl field5)
        {
            field5.Name = "housenumber";
            field5.Text = ((string)(this.field6_Create().ProvideValue(new Neptuo.Templates.Extensions.DefaultMarkupExtensionContext(field5, field5.GetType().GetProperty("Text"), this.dependencyProvider))));
        }
        private TestConsoleNG.Extensions.BindingExtension field6_Create()
        {
            TestConsoleNG.Extensions.BindingExtension field6 = new TestConsoleNG.Extensions.BindingExtension(((TestConsoleNG.Data.DataStorage)(this.dependencyProvider.Resolve(typeof(TestConsoleNG.Data.DataStorage), null))));
            field6.Expression = "HouseNumber";
            return field6;
        }
        private TestConsoleNG.Controls.PanelControl field7_Create()
        {
            TestConsoleNG.Controls.PanelControl field7 = new TestConsoleNG.Controls.PanelControl(this.componentManager);
            this.componentManager.AddComponent(field7, this.field7_Bind);
            return field7;
        }
        private void field7_Bind(TestConsoleNG.Controls.PanelControl field7)
        {
            field7.Content = new System.Collections.Generic.List<object>();
            field7.Content.Add(" \r\n        City: \r\n        ");
            field7.Content.Add(this.field8_Create());
        }
        private TestConsoleNG.Controls.TextBoxControl field8_Create()
        {
            TestConsoleNG.Controls.TextBoxControl field8 = new TestConsoleNG.Controls.TextBoxControl(this.componentManager);
            this.componentManager.AddComponent(field8, this.field8_Bind);
            return field8;
        }
        private void field8_Bind(TestConsoleNG.Controls.TextBoxControl field8)
        {
            field8.Name = "city";
            field8.Text = ((string)(this.field9_Create().ProvideValue(new Neptuo.Templates.Extensions.DefaultMarkupExtensionContext(field8, field8.GetType().GetProperty("Text"), this.dependencyProvider))));
        }
        private TestConsoleNG.Extensions.BindingExtension field9_Create()
        {
            TestConsoleNG.Extensions.BindingExtension field9 = new TestConsoleNG.Extensions.BindingExtension(((TestConsoleNG.Data.DataStorage)(this.dependencyProvider.Resolve(typeof(TestConsoleNG.Data.DataStorage), null))));
            field9.Expression = "City";
            return field9;
        }
        private TestConsoleNG.Controls.PanelControl field10_Create()
        {
            TestConsoleNG.Controls.PanelControl field10 = new TestConsoleNG.Controls.PanelControl(this.componentManager);
            this.componentManager.AddComponent(field10, this.field10_Bind);
            return field10;
        }
        private void field10_Bind(TestConsoleNG.Controls.PanelControl field10)
        {
            field10.Content = new System.Collections.Generic.List<object>();
            field10.Content.Add("\r\n        Postal code:\r\n        ");
            field10.Content.Add(this.field11_Create());
        }
        private TestConsoleNG.Controls.TextBoxControl field11_Create()
        {
            TestConsoleNG.Controls.TextBoxControl field11 = new TestConsoleNG.Controls.TextBoxControl(this.componentManager);
            this.componentManager.AddComponent(field11, this.field11_Bind);
            return field11;
        }
        private void field11_Bind(TestConsoleNG.Controls.TextBoxControl field11)
        {
            field11.Name = "postalcode";
            field11.Text = ((string)(this.field12_Create().ProvideValue(new Neptuo.Templates.Extensions.DefaultMarkupExtensionContext(field11, field11.GetType().GetProperty("Text"), this.dependencyProvider))));
        }
        private TestConsoleNG.Extensions.BindingExtension field12_Create()
        {
            TestConsoleNG.Extensions.BindingExtension field12 = new TestConsoleNG.Extensions.BindingExtension(((TestConsoleNG.Data.DataStorage)(this.dependencyProvider.Resolve(typeof(TestConsoleNG.Data.DataStorage), null))));
            field12.Expression = "PostalCode";
            return field12;
        }
    }
}
