/*Generated by SharpKit 5 v5.2.0*/
function DefaultClient_Load()
{
    $(document.body).append("Ready<br/>");
};
function btnTest_click(e)
{
    var componentManager = new Neptuo.Templates.ComponentManager.ctor();
    var view = new Neptuo.Templates.View_C612CAF502A06BAAC6171B58D1EA2F61EC9D6D55.ctor();
    view.Setup(new Neptuo.Templates.BaseViewPage.ctor(componentManager), componentManager, null);
    view.CreateControls();
    view.Init();
    view.Render(new Neptuo.Templates.HtmlTextWriter.ctor$$TextWriter(null));
    view.Dispose();
};
