/*Generated by SharpKit 5 v5.2.0*/
function DefaultClient_Load()
{
    $(document.body).append("Ready<br/>");
};
function btnTest_click(e)
{
    var componentManager = new Neptuo.Templates.ComponentManager.ctor();
};
