//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neptuo.Web.Framework
{
    using System;
    using Neptuo.Web;
    using Neptuo.Web.Framework;
    using Neptuo.Web.Framework.Controls;
    using Neptuo.Web.Framework.Extensions;
    using Neptuo.Web.Framework.Observers;
    using System.Collections.Generic;

    public sealed class GeneratedView : Neptuo.Web.Framework.BaseGeneratedView, Neptuo.Web.Framework.IGeneratedView, System.IDisposable
    {
        private PanelControl field1;
        private VisibleObserver field2;
        private TextBoxControl field3;
        private BindingExtension field4;
        private ValidationObserver field5;

        private AnchorControl field6;
        private Parameter field7;
        private Parameter field8;
        private Security field9;

        protected override void CreateViewPageControls()
        {
            viewPage.Content = new List<object>();

            field1 = new PanelControl();
            componentManager.AddComponent(field1, field1_Bind);
            viewPage.Content.Add(field1);

            field6 = new AnchorControl();
            componentManager.AddComponent(field6, field6_Bind);
            viewPage.Content.Add(field6);
        }

        private void field1_Bind()
        {
            field1.ComponentManager = componentManager;
            field1.Content = new List<object>();

            field3 = new TextBoxControl();
            componentManager.AddComponent(field3, field3_Bind);
            ((List<object>)field1.Content).Add(field3);

            field2 = new VisibleObserver();
            componentManager.AttachObserver(field1, field2, field2_Bind);
        }

        private void field2_Bind()
        {
            field2.Visible = true;
        }

        private void field3_Bind()
        {
            field3.ComponentManager = componentManager;
            field3.Name = "FullName";

            field4 = new BindingExtension();
            field4_Bind();
            field3.Text = (string)field4.ProvideValue(null);
            
            field5 = new ValidationObserver();
            componentManager.AttachObserver(field3, field5, field5_Bind);
            componentManager.AttachObserver(field3, field5, field5_Bind2);
            componentManager.AttachObserver(field3, field5, field5_Bind3);
        }

        private void field4_Bind()
        {
            field4.Expression = "John Doe";
        }

        private void field5_Bind()
        {
            field5.MinLength = 2;
        }

        private void field5_Bind2()
        {
            field5.MaxLength = 10;
        }

        private void field5_Bind3()
        {
            field5.ErrorMessage = "Provide a valid value!";
        }

        private void field6_Bind()
        {
            field6.ComponentManager = componentManager;
            field6.Url = "~/Admin";
            field6.Parameters = new List<Parameter>();

            field7 = new Parameter();
            componentManager.AddComponent(field7, field7_Bind);
            field6.Parameters.Add(field7);

            field8 = new Parameter();
            componentManager.AddComponent(field8, field8_Bind);
            field6.Parameters.Add(field8);

            field9 = new Security();
            componentManager.AddComponent(field9, field9_Bind);
            field6.Security = field9;
        }

        private void field7_Bind()
        {
            field7.Name = "ID";
            field7.Value = "5";
        }

        private void field8_Bind()
        {
            field8.Name = "Detail";
            field8.Value = "True";
        }

        private void field9_Bind()
        {
            field9.Identifier = "Hello";
        }
    }
}
