/* Generated by SharpKit 5 v5.4.4 */

function DefaultClient_Load(){
    $(document.body).append("Ready<br/>");
};
function btnTest_click(e){
    var container = new Test.Templates.UI.SimpleContainer.SimpleObjectBuilder.ctor();
    Neptuo._DependencyContainerExtensions.RegisterInstance$1(Test.Templates.UI.Data.DataStorage.ctor, container, new Test.Templates.UI.Data.DataStorage.ctor(new Test.Templates.UI.Models.PersonModel.ctor("Jon", "Doe", new Test.Templates.UI.Models.AddressModel.ctor("Dlouhá street", 23, "Prague", 10001))));
    Neptuo._DependencyContainerExtensions.RegisterInstance$1(Test.Templates.UI.Converters.IValueConverterService.ctor, container, new Test.Templates.UI.Converters.ValueConverterService.ctor().SetConverter("NullToBool", new Test.Templates.UI.Converters.NullToBoolValueConverter.ctor()));
    Neptuo._DependencyContainerExtensions.RegisterInstance$1(Test.Templates.IComponentManager.ctor, container, new Test.Templates.Runtime.ComponentManager.ctor());
    var writer = new System.IO.StringWriter.ctor();
    $("#viewContent").html(writer.toString());
};

