/* Generated by SharpKit 5 v5.4.4 */
if (typeof($CreateException)=='undefined') 
{
    var $CreateException = function(ex, error) 
    {
        if(error==null)
            error = new Error();
        if(ex==null)
            ex = new System.Exception.ctor();       
        error.message = ex.message;
        for (var p in ex)
           error[p] = ex[p];
        return error;
    }
}


function DefaultClient_Load(){
    $(document.body).append("Ready<br/>");
};
function btnTest_click(e){
    throw $CreateException(new System.NotImplementedException.ctor(), new Error());
    var container = null;
    var writer = new System.IO.StringWriter.ctor();
    $("#viewContent").html(writer.toString());
};

