using TestConsoleNG;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neptuo.Templates
{
    using System;
    using Neptuo.Templates;
    using Neptuo.Templates.Controls;
    
    //public sealed class View_7D2EFEF4F3AB0B8A114C713D7C4C8F06E0F3A0F7 : Neptuo.Templates.BaseGeneratedView, Neptuo.Templates.IGeneratedView, System.IDisposable
    //{
    //    protected override void CreateViewPageControls()
    //    {
    //        this.Content.Add(this.field1_Create());
    //    }
    //    private PanelControl field1_Create()
    //    {
    //        PanelControl field1 = new PanelControl(this.componentManager);
    //        field1.Content = new System.Collections.Generic.List<object>();
    //        this.componentManager.AddComponent<PanelControl>(field1, this.field1_Bind);
    //        return field1;
    //    }
    //    private void field1_Bind(PanelControl field1)
    //    {
    //        field1.SetAttribute("class", "checkin");
    //        field1.Content.Add(this.field2_Create());
    //    }
    //    private GenericContentControl field2_Create()
    //    {
    //        GenericContentControl field2 = new GenericContentControl(this.componentManager);
    //        componentManager.AddComponent<GenericContentControl>(field2, this.field2_Bind);
    //        return field2;
    //    }
    //    private void field2_Bind(GenericContentControl field2)
    //    {
    //        field2.TagName = "a";
    //        field2.SetAttribute("href", "google");
    //        field2.Content = new System.Collections.Generic.List<object>();
    //        field2.Content.Add("Hello, World!");
    //    }
    //}
}
